export enum ErrorMessageCode {
    STUDENT_ALREADY_EXISTS = "STUDENT_ALREADY_EXISTS",
    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
    INVALID_TOKEN = "INVALID_TOKEN"
}