export enum ErrorMessageCode {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    INCORRECT_PASSWORD = "INCORRECT_PASSWORD",
    INVALID_TOKEN = "INVALID_TOKEN"
}